In [24]:
for t in range(10):
    s = 10-1-t
    print(s)

9
8
7
6
5
4
3
2
1
0


In [23]:
import numpy as np

sol = np.load("solutions/epoch1_solution.npz")

print(sol['model'])

[[ 1.75278533  0.40037501  0.96031382]
 [ 2.11509413  1.86772317 -1.19407843]
 [ 0.74053915 -0.01290831 -0.46549918]
 [ 0.39072059  0.14974877  1.42107341]]
